version: 2.1

orbs:
  python: circleci/python@1.2

environment:
  DJANGO_SETTINGS_MODULE: config.settings

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
        environment:
          DATABASE_URL: postgresql://root@localhost/coinspace_test
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: XU7db6BTsc
          POSTGRES_DB: coinspace_test
    environment:
      SECRET_KEY: DiRR${VXyaEKW:,iqIf]=3G+kc%(0-
      DB_USER: root
      DB_PWD: XU7db6BTsc
      COINMARKETCAP_API_KEY: dc066f41-8a46-4bda-92e6-6be9223e68b7
      ETHERSCAN_API_KEY: JVZ59N9CEMX2I9JEBEA121473QEV2VH6WY
      POLYGONSCAN_API_KEY: U7SJM348V4SFMZ95DSPIY23UJXU9KNRBEU
      SNOWTRACE_API_KEY: J8QQ4DS4HUFMQEB1J21S8VZBAPGT6FY8BU

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Create migration directories
          command: |
            mkdir account/migrations
            touch account/migrations/__init__.py
            mkdir home/migrations
            touch home/migrations/__init__.py
            mkdir tracker/migrations
            touch tracker/migrations/__init__.py
      - run:
          name: Make migrations
          command: python manage.py makemigrations
      - run:
          name: Migrate
          command: python manage.py migrate
      - run:
          name: Run tests
          command: pytest tests/unit
      - run:
          name: Check PEP8
          command: flake8

workflows:
  sample:
    jobs:
      - build-and-test
