version: 2.1

orbs:
  python: circleci/python@1.2

environment:
  DJANGO_SETTINGS_MODULE: config.settings

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
        environment:
          DATABASE_URL: postgresql://root@localhost/coinspace_test
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: XU7db6BTsc
          POSTGRES_DB: coinspace_test

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for database initialization
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: pytest tests/unit
          environment:
            SECRET_KEY: DiRR${VXyaEKW:,iqIf]=3G+kc%(0-
            DB_USER: root
            DB_PWD: XU7db6BTsc
            COINMARKETCAP_API_KEY: ot6mVCthSpu9RgiTLSWIHjlI7KlpqpES
            ETHERSCAN_API_KEY: ahE0AaSjPzBkSUwhj3e05nSocaeIfN34
            POLYGONSCAN_API_KEY: 4eAxFNj4gCdVxaWgenMafAp6DoVGFT5Y
            SNOWTRACE_API_KEY: DVDM1OKivUnqcSNWBcjU49XDswhzz3b3
      - run:
          name: Check PEP8
          command: flake8

workflows:
  sample:
    jobs:
      - build-and-test
