version: 2.1

orbs:
  python: circleci/python@1.2

environment:
  DJANGO_SETTINGS_MODULE: config.settings

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
        environment:
          DATABASE_URL: postgresql://root@localhost/coinspace_test
      - image: cimg/postgres:14.2.0
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: XU7db6BTsc
          POSTGRES_DB: coinspace_test

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest tests/unit
          environment:
            SECRET_KEY: DiRR${VXyaEKW:,iqIf]=3G+kc%(0-
            DB_USER: root
            DB_PWD: XU7db6BTsc
            COINMARKETCAP_API_KEY: ot6mVCthSpu9RgiTLSWIHjlI7KlpqpES
            ETHERSCAN_API_KEY: ahE0AaSjPzBkSUwhj3e05nSocaeIfN34
            POLYGONSCAN_API_KEY: 4eAxFNj4gCdVxaWgenMafAp6DoVGFT5Y
            SNOWTRACE_API_KEY: DVDM1OKivUnqcSNWBcjU49XDswhzz3b3
      - run:
          name: Check PEP8
          command: flake8

workflows:
  sample:
    jobs:
      - build-and-test
